version: "3"

services:
  backend:
    build:
      context: ./api-challenge
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "3000:3000"
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend-challenge
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "3001:80"
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
